<?php
/** @var \Eloom\PayUAttributes\Block\Customer\Widget\DniType $block */
?>
<div class="field dnitype<?= $block->isRequired() ? ' required' : '' ?>">
	<label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('dnitype')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('dnitype')) ?></span></label>
	<div class="control">
		<select id="<?= $block->escapeHtmlAttr($block->getFieldId('dnitype')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('dnitype')) ?>"
		        title="<?= $block->escapeHtmlAttr($block->getStoreLabel('dnitype')) ?>"<?php if ($block->isRequired()) : ?> class="validate-select" data-validate="{required:true}"<?php endif; ?>>
			<?php $options = $block->getDnitypeOptions(); ?>
			<?php $value = $block->getDnitype(); ?>
			<?php foreach ($options as $option) : ?>
				<option
						value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?= ($option->getValue() == $value) ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
			<?php endforeach; ?>
		</select>
	</div>
</div>
